=== ana-rabelo/TAP_project_v1.0/files/agenda.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.dei.isep.ipp.pt/tap-2023"
        xmlns:tns="http://www.dei.isep.ipp.pt/tap-2023" elementFormDefault="qualified">
    <element name="agenda" type="tns:agendaType"/>

    <complexType name="agendaType">
        <sequence>
            <element type="tns:aircraftsType" name="aircrafts"/>
            <element type="tns:runwaysType" name="runways"/>
        </sequence>
        <attribute type="positiveInteger" name="maximumDelayTime" use="required"/>
    </complexType>
    
    <complexType name="aircraftsType">
        <sequence>
            <element type="tns:aircraftType" name="aircraft" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    
    <complexType name="runwaysType">
        <sequence>
            <element type="tns:runwayType" name="runway" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    
    <complexType name="aircraftType">
        <simpleContent>
            <extension base="string">
                <attribute type="string" name="id" use="required"/>
                <attribute type="tns:classType" name="class" use="required"/>
                <attribute type="nonNegativeInteger" name="target" use="required"/>
                <attribute type="positiveInteger" name="emergency" use="optional"/>
            </extension>
        </simpleContent>
    </complexType>
    
    <complexType name="runwayType">
        <sequence>
            <element type="tns:handlesType" name="handles" maxOccurs="unbounded"/>
        </sequence>
        <attribute type="string" name="id" use="required"/>
    </complexType>
    
    <complexType name="handlesType">
        <simpleContent>
            <extension base="string">
                <attribute type="tns:classType" name="class"/>
            </extension>
        </simpleContent>
    </complexType>
    
    <simpleType name="classType">
        <restriction base="byte">
            <minInclusive value="1"/>
            <maxInclusive value="6"/>
        </restriction>
    </simpleType>
    
</schema>

=== ana-rabelo/TAP_project_v1.0/files/assessment/ms01/valid00_in.xml
<?xml version="1.0" encoding="UTF-8"?>
<agenda maximumDelayTime="900" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.dei.isep.ipp.pt/tap-2023" xsi:schemaLocation="http://www.dei.isep.ipp.pt/tap-2023 ../../agenda.xsd">
    <aircrafts>
        <aircraft id="A1" class="5" target="1"/>
        <aircraft id="A2" class="2" target="15"/>
        <aircraft id="A3" class="3" target="104"/>
        <aircraft id="A4" class="1" target="139" emergency="5"/>
        <aircraft id="A5" class="2" target="151"/>
    </aircrafts>
    <runways>
        <runway id="R1">
            <handles class="1"/>
            <handles class="2"/>
            <handles class="3"/>
            <handles class="4"/>
            <handles class="5"/>
            <handles class="6"/>
        </runway>
        <runway id="R2">
            <handles class="1"/>
            <handles class="2"/>
            <handles class="3"/>            
            <handles class="4"/>
            <handles class="5"/>
        </runway>
    </runways>
</agenda>

=== ana-rabelo/TAP_project_v1.0/files/assessment/ms01/valid01_in.xml
<?xml version="1.0" encoding="UTF-8"?>
<agenda maximumDelayTime="900" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.dei.isep.ipp.pt/tap-2023" xsi:schemaLocation="http://www.dei.isep.ipp.pt/tap-2023 ../../agenda.xsd">
    <aircrafts>
        <aircraft id="1" class="1" target="0"/>
        <aircraft id="2" class="1" target="5"/>
        <aircraft id="3" class="4" target="45"/>
        <aircraft id="4" class="5" target="50"/>
        <aircraft id="5" class="3" target="100"/>
    </aircrafts>
    <runways>
        <runway id="1">
            <handles class="1"/>
            <handles class="2"/>
            <handles class="3"/>
            <handles class="4"/>
            <handles class="5"/>
            <handles class="6"/>
        </runway>
        <runway id="2">
            <handles class="1"/>
            <handles class="2"/>
            <handles class="3"/>
            <handles class="4"/>
            <handles class="5"/>
            <handles class="6"/>
        </runway>
    </runways>
</agenda>
